server:
  port: 9527

eureka:
  client:
    service-url:
        #defaultZone: http://localhost:7001/eureka
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuui-9527.com
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: springcloud
  company.name: www.ajacom.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring:
  application:
    name: gateway-zuui

zuul:
  routes:
    mydept.serviceId: dept-provider
    mydept.path: /mydept/**
  ignored-services: "*"

